### ISSUE TITLE
在线 demo 打开报错

### ISSUE THREAD

**Issue by JohnieXu** [imgcook/imove#67]
README 中提供的 demo 地址打开报错 https://65hzt.sse.codesandbox.io/

```
ℹ Compiling Webpack
[1] ✔ Webpack: Compiled with some errors in 36.61s
[1]  ERROR  Failed to compile with 3 errors10:27:34 PM
[1]
[1] These dependencies were not found:
[1]
[1] * fr-generator in ./packages/core/dist/core.esm.js
[1] * react-split-pane/lib/Pane in ./packages/core/dist/core.esm.js
[1] * react-split-pane/lib/SplitPane in ./packages/core/dist/core.esm.js
[1]
[1] To install them, you can run: npm install --save fr-generator react-split-pane/lib/Pane react-split-pane/lib/SplitPane
[1] (node:405) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: chunk of umi not found.
[1]     at htmlChunks.forEach (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:104:27)
[1]     at Array.forEach (<anonymous>)
[1]     at chunksToFiles (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:93:14)
[1]     at /sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:188:32
[1]     at Generator.next (<anonymous>)
[1]     at asyncGeneratorStep (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:62:103)
[1]     at _next (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:64:194)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] (node:405) UnhandledPromiseRejectionWarning: Unhandledpromise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[1] (node:405) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1] (node:405) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: chunk of umi not found.
[1]     at htmlChunks.forEach (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:104:27)
[1]     at Array.forEach (<anonymous>)
[1]     at chunksToFiles (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:93:14)
[1]     at /sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:188:32
[1]     at Generator.next (<anonymous>)
[1]     at asyncGeneratorStep (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:62:103)
[1]     at _next (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:64:194)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] (node:405) UnhandledPromiseRejectionWarning: Unhandledpromise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
[1] (node:405) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: chunk of umi not found.
[1]     at htmlChunks.forEach (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:104:27)
[1]     at Array.forEach (<anonymous>)
[1]     at chunksToFiles (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:93:14)
[1]     at /sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:188:32
[1]     at Generator.next (<anonymous>)
[1]     at asyncGeneratorStep (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:62:103)
[1]     at _next (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:64:194)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] (node:405) UnhandledPromiseRejectionWarning: Unhandledpromise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
[1] (node:405) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: chunk of umi not found.
[1]     at htmlChunks.forEach (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:104:27)
[1]     at Array.forEach (<anonymous>)
[1]     at chunksToFiles (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:93:14)
[1]     at /sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:188:32
[1]     at Generator.next (<anonymous>)
[1]     at asyncGeneratorStep (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:62:103)
[1]     at _next (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:64:194)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] (node:405) UnhandledPromiseRejectionWarning: Unhandledpromise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
[1] (node:405) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: chunk of umi not found.
[1]     at htmlChunks.forEach (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:104:27)
[1]     at Array.forEach (<anonymous>)
[1]     at chunksToFiles (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:93:14)
[1]     at /sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:188:32
[1]     at Generator.next (<anonymous>)
[1]     at asyncGeneratorStep (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:62:103)
[1]     at _next (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:64:194)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] (node:405) UnhandledPromiseRejectionWarning: Unhandledpromise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
[1] (node:405) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: chunk of umi not found.
[1]     at htmlChunks.forEach (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:104:27)
[1]     at Array.forEach (<anonymous>)
[1]     at chunksToFiles (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:93:14)
[1]     at /sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:188:32
[1]     at Generator.next (<anonymous>)
[1]     at asyncGeneratorStep (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:62:103)
[1]     at _next (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:64:194)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] (node:405) UnhandledPromiseRejectionWarning: Unhandledpromise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
[1] (node:405) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: chunk of umi not found.
[1]     at htmlChunks.forEach (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:104:27)
[1]     at Array.forEach (<anonymous>)
[1]     at chunksToFiles (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:93:14)
[1]     at /sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:188:32
[1]     at Generator.next (<anonymous>)
[1]     at asyncGeneratorStep (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:62:103)
[1]     at _next (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:64:194)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] (node:405) UnhandledPromiseRejectionWarning: Unhandledpromise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
[1] (node:405) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: chunk of umi not found.
[1]     at htmlChunks.forEach (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:104:27)
[1]     at Array.forEach (<anonymous>)
[1]     at chunksToFiles (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:93:14)
[1]     at /sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:188:32
[1]     at Generator.next (<anonymous>)
[1]     at asyncGeneratorStep (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:62:103)
[1]     at _next (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:64:194)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] (node:405) UnhandledPromiseRejectionWarning: Unhandledpromise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
[1] (node:405) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: chunk of umi not found.
[1]     at htmlChunks.forEach (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:104:27)
[1]     at Array.forEach (<anonymous>)
[1]     at chunksToFiles (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:93:14)
[1]     at /sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:188:32
[1]     at Generator.next (<anonymous>)
[1]     at asyncGeneratorStep (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:62:103)
[1]     at _next (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:64:194)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] (node:405) UnhandledPromiseRejectionWarning: Unhandledpromise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
[1] (node:405) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: chunk of umi not found.
[1]     at htmlChunks.forEach (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:104:27)
[1]     at Array.forEach (<anonymous>)
[1]     at chunksToFiles (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:93:14)
[1]     at /sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:188:32
[1]     at Generator.next (<anonymous>)
[1]     at asyncGeneratorStep (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:62:103)
[1]     at _next (/sandbox/node_modules/@umijs/preset-built-in/lib/plugins/commands/htmlUtils.js:64:194)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] (node:405) UnhandledPromiseRejectionWarning: Unhandledpromise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
```

**Comment by iloveyou11** [comment]
已解决，可以访问线上地址：https://oyg3y.sse.codesandbox.io/
